apiVersion: v1
entries:
  elasticsearch:
  - annotations:
      category: Analytics
    apiVersion: v2
    appVersion: 7.10.2
    created: "2021-03-15T23:45:10.295698+09:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: global.kibanaEnabled
      name: kibana
      repository: https://charts.bitnami.com/bitnami
      version: 7.x.x
    description: A highly scalable open-source full-text search and analytics engine
    digest: f47433441df22a2ba3b5f38901f840dd589c7ad9e932b34e22b83384c32ffabc
    home: https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch
    icon: https://bitnami.com/assets/stacks/elasticsearch/img/elasticsearch-stack-220x234.png
    keywords:
    - elasticsearch
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: elasticsearch
    sources:
    - https://github.com/bitnami/bitnami-docker-elasticsearch
    - https://www.elastic.co/products/elasticsearch
    urls:
    - https://github.com/TWpower/helm-repo/releases/download/release-tag/elasticsearch-14.5.0.tgz
    version: 14.5.0
  kafka:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 2.7.0
    created: "2021-03-15T23:45:10.302333+09:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: zookeeper.enabled
      name: zookeeper
      repository: https://charts.bitnami.com/bitnami
      version: 6.x.x
    description: Apache Kafka is a distributed streaming platform.
    digest: 83c1514423a7f656cc105f5a14b70044bfc31c1da8fc48c16a8bcfc7e313d5d1
    home: https://github.com/bitnami/charts/tree/master/bitnami/kafka
    icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-220x234.png
    keywords:
    - kafka
    - zookeeper
    - streaming
    - producer
    - consumer
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: kafka
    sources:
    - https://github.com/bitnami/bitnami-docker-kafka
    - https://kafka.apache.org/
    urls:
    - https://github.com/TWpower/helm-repo/releases/download/release-tag/kafka-12.11.1.tgz
    version: 12.11.1
  mariadb:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 10.5.9
    created: "2021-03-15T23:45:10.304778+09:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Fast, reliable, scalable, and easy to use open-source relational database system. MariaDB Server is intended for mission-critical, heavy-load production systems as well as for embedding into mass-deployed software. Highly available MariaDB cluster.
    digest: 194341a4ad52650ac859b977b6df4472a489ec92a132f48e645ff9fc5f9e356e
    home: https://github.com/bitnami/charts/tree/master/bitnami/mariadb
    icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: mariadb
    sources:
    - https://github.com/bitnami/bitnami-docker-mariadb
    - https://github.com/prometheus/mysqld_exporter
    - https://mariadb.org
    urls:
    - https://github.com/TWpower/helm-repo/releases/download/release-tag/mariadb-9.3.5.tgz
    version: 9.3.5
generated: "2021-03-15T23:45:10.285944+09:00"
